# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 17:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40)),
                ('last_name', models.CharField(blank=True, max_length=40)),
                ('date_of_birth', models.DateTimeField()),
                ('email', models.CharField(blank=True, max_length=40)),
                ('jabber', models.CharField(blank=True, max_length=40)),
                ('skype', models.CharField(blank=True, max_length=40)),
                ('other_contats', models.TextField()),
                ('bio', models.TextField()),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_profiles',
            },
        ),
    ]
